apiVersion: v1
kind: Secret
metadata:
  name: hr-ragwiser-secret
  namespace: hr-ragwiser
type: Opaque
data:
  # Base64 encoded values
  # postgres = cG9zdGdyZXM=
  # To create your own: echo -n 'your-password' | base64
  POSTGRES_PASSWORD: your-password
  SPRING_DATASOURCE_PASSWORD: your-password

